web:
  image: nginx:1-alpine
  ports:
    - "8080:80"
  links:
    - php
  volumes:
    - ./code:/code
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
php:
  image: php:7.2-fpm-alpine3.8
  volumes:
    - ./code:/code